services:

  jupyter:
    build: .
    container_name: jupyter-mlops
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/jovyan/work
      - ./data:/home/jovyan/data
      - ./models:/home/jovyan/models
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    depends_on:
      - spark
      - postgres
      - mlflow
    restart: unless-stopped


  spark:
    image: apache/spark:3.5.1
    container_name: spark-mlops
    command: >
      /opt/spark/bin/spark-class
      org.apache.spark.deploy.master.Master
    ports:
      - "7077:7077"
      - "8080:8080"
    volumes:
      - ./data:/data
    restart: unless-stopped

  postgres:
    image: postgres:15
    container_name: postgres-mlops
    environment:
      POSTGRES_USER: mlops
      POSTGRES_PASSWORD: mlops
      POSTGRES_DB: mlops_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  mlflow:
    build:
      context: .
      dockerfile: Dockerfile.mlflow
    container_name: mlflow-mlops
    ports:
      - "5000:5000"
    command: >
      mlflow server
      --backend-store-uri postgresql://mlops:mlops@postgres:5432/mlops_db
      --default-artifact-root /mlflow/artifacts
      --host 0.0.0.0
    depends_on:
      - postgres
    volumes:
      - ./mlflow:/mlflow
    restart: unless-stopped

  # Pipeline ML automatique
  ml-pipeline:
    build:
      context: .
      dockerfile: Dockerfile.pipeline
    container_name: ml-pipeline-mlops
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    depends_on:
      - mlflow
      - postgres
    volumes:
      - ./data:/app/data
      - ./models:/app/models
      - ./deployment_gcp:/app/deployment_gcp
    # Pour ex√©cution manuelle: docker-compose run ml-pipeline
    profiles:
      - manual

volumes:
  postgres_data:
